function dynamics = f_lin(in1,U1,U2,U3)
%F_LIN
%    DYNAMICS = F_LIN(IN1,U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Mar-2017 11:52:05

x1 = in1(:,1);
x2 = in1(:,2);
x3 = in1(:,3);
t2 = U2-x2;
dynamics = [x2;U1.*5.857087075361187e1-x1.*6.403474914374016e1-x2.*6.507874528179097e-1+t2.*x3.*abs(t2).*3.369562364742736;0.0];
