function dynamics = f(in1,U1,U2,U3)
%F
%    DYNAMICS = F(IN1,U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-May-2017 14:54:04

x1 = in1(:,1);
x2 = in1(:,2);
x3 = in1(:,3);
t2 = U2-x2;
dynamics = [x2;U3.*1.035094933645274-x1.*3.969012768112264e1+t2.*x3.*abs(t2).*2.088527905152551;0.0];
