function Jacob_f = Jacob_f(in1,U1,U2,U3)
%JACOB_F
%    JACOB_F = JACOB_F(IN1,U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-May-2017 14:54:04

x2 = in1(:,2);
x3 = in1(:,3);
t2 = U2-x2;
t3 = abs(t2);
Jacob_f = reshape([0.0,-3.969012768112264e1,0.0,1.0,t3.*x3.*(-2.088527905152551)-t2.*x3.*sign(t2).*2.088527905152551,0.0,0.0,t2.*t3.*2.088527905152551,0.0],[3,3]);
