function Jacob_h = Jacob_h(in1)
%JACOB_H
%    JACOB_H = JACOB_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-May-2017 14:54:05

Jacob_h = reshape([1.0,0.0,0.0,1.0,0.0,0.0],[2,3]);
