function output = h_lin(in1)
%H_LIN
%    OUTPUT = H_LIN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Mar-2017 11:52:05

x1 = in1(:,1);
x2 = in1(:,2);
output = [x1;x2];
