function Jacob_h = Jacob_h_lin(in1)
%JACOB_H_LIN
%    JACOB_H = JACOB_H_LIN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Mar-2017 11:52:05

Jacob_h = reshape([1.0,0.0,0.0,1.0,0.0,0.0],[2,3]);
