function Jacob_f = Jacob_f_lin(in1,U1,U2,U3)
%JACOB_F_LIN
%    JACOB_F = JACOB_F_LIN(IN1,U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Mar-2017 11:52:05

x2 = in1(:,2);
x3 = in1(:,3);
t2 = U2-x2;
t3 = abs(t2);
Jacob_f = reshape([0.0,-6.403474914374016e1,0.0,1.0,t3.*x3.*(-3.369562364742736)-t2.*x3.*sign(t2).*3.369562364742736-6.507874528179097e-1,0.0,0.0,t2.*t3.*3.369562364742736,0.0],[3,3]);
