function output = h(in1)
%H
%    OUTPUT = H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Apr-2017 21:14:20

x1 = in1(:,1);
x2 = in1(:,2);
output = [x1;x2];
