function Jacob_h = Jacob_h(in1)
%JACOB_H
%    JACOB_H = JACOB_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    22-Aug-2017 17:14:20

Jacob_h = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
